routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::resource('/','RestoController');
Route::resource('resto','RestoController');

app/Resto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Resto extends Model
{
    protected $table = 'resto';
    protected $fillable = [
        'name', 'lat', 'lng', 'address'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/RestoController.php
<?php
  
namespace App\Http\Controllers;
  
use App\Resto;
use App\Http\Requests\RestoRequest;
use Illuminate\Http\Request;
  
class RestoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $resto = Resto::latest()->paginate(5);
  
        return view('resto.index',compact('resto'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('resto.create');
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RestoRequest $request)
    {
  
        Resto::create($request->all());
   
        return redirect()->route('resto.index')
                        ->with('success','Resto created successfully.');
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \App\Resto  $resto
     * @return \Illuminate\Http\Response
     */
    public function show(Resto $resto)
    {
        return view('resto.show',compact('resto'));
    }
   
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Resto  $resto
     * @return \Illuminate\Http\Response
     */
    public function edit(Resto $resto)
    {
        return view('resto.edit',compact('resto'));
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Resto  $resto
     * @return \Illuminate\Http\Response
     */
    public function update(RestoRequest $request, Resto $resto)
    {
        $request->validate([
            'name' => 'required',
            'lat' => 'required',
            'lng' => 'required',
        ]);
  
        $resto->update($request->all());
  
        return redirect()->route('resto.index')
                        ->with('success','Resto updated successfully');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Resto  $resto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Resto $resto)
    {
        $resto->delete();
  
        return redirect()->route('resto.index')
                        ->with('success','Resto deleted successfully');
    }
}

resources/views/resto/create.blade.php
@extends('resto.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Resto</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('resto.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('resto.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Latitude:</strong>
                <input type="text" name="lat" class="form-control" placeholder="Latitude">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Longitude:</strong>
                <input type="text" name="lng" class="form-control" placeholder="Longitude">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Address:</strong>
                <textarea class="form-control" style="height:150px" name="address" placeholder="Address"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/resto/edit.blade.php
@extends('resto.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Resto</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('resto.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('resto.update',$resto->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $resto->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
             <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Latitude:</strong>
                <input type="text" name="lat" value="{{ $resto->lat }}" class="form-control" placeholder="Latitude">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Longitude:</strong>
                <input type="text" name="lng" value="{{ $resto->lng }}" class="form-control" placeholder="Longitude">
            </div>
        </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Address:</strong>
                    <textarea class="form-control" style="height:150px" name="detail" placeholder="Address">{{ $resto->address }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/resto/index.blade.php
@extends('resto.layout')
 
@section('content')
    
    <div class="row">
        <br> &nbsp;
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Map</h2>
            </div>
            
        </div>
    </div>
    <div class="row">
        <div id="map" style="width: 100%; height: 500px;"></div>
    </div>
    <div class="col-lg-12 margin-tb">
         <br> &nbsp;
            <div class="pull-left">
                <h2>Restaurant Management</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('resto.create') }}"> Create New Resto</a>
            </div>
        </div>
   <br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Address</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($resto as $resto_data)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $resto_data->name }}</td>
            <td>{{ $resto_data->lat }}</td>
            <td>{{ $resto_data->lng }}</td>
            <td>{{ $resto_data->address }}</td>
            <td>
                <form action="{{ route('resto.destroy',$resto_data->id) }}" method="POST">
   
                    <a class="btn btn-info btn-sm" href="{{ route('resto.show',$resto_data->id) }}">Get Direction</a>
    
                    <a class="btn btn-primary btn-sm" href="{{ route('resto.edit',$resto_data->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>

   


<script>
  var map;

  function initMap() {
      
      var southeast_asia =  {lat: -0.689093, lng: 106.750281};
      map = new google.maps.Map(document.getElementById('map'), {
           center:southeast_asia,
           zoom: 5.5,
      });

      var markers = locations.map(function(location, i) {
          return new google.maps.Marker({
              position: location,
              label: location.label
          });
      });

      var markerCluster = new MarkerClusterer(map, markers, {
          imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'
      });
  }

  var locations = [
       @foreach ($resto as $resto_data)
        {lat: {{ $resto_data->lat }}, lng: {{ $resto_data->lng }}, label: '{{ $resto_data->name }}'},
       @endforeach
                 ]
        
</script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"> </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlfh4WuZJz51yTzzIiopDiWIA1CmntLC0&callback=initMap" sync defer></script>
  
    {!! $resto->links() !!}
      
@endsection

resources/views/resto/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Gery's Assignment
 </title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

resources/views/resto/show.blade.php
@extends('resto.layout')
<style>
      #right-panel {
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }

      #right-panel select, #right-panel input {
        font-size: 15px;
      }

      #right-panel select {
        width: 100%;
      }

      #right-panel i {
        font-size: 12px;
      }
      #map {
        height: 100%;
        float: left;
        width: 63%;
        height: 100%;
      }
      #right-panel {
        float: right;
        width: 34%;
        height: 100%;
      }
      .panel {
        height: 100%;
        overflow: auto;
      }
    </style>
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Direction</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('resto.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div id="map"></div>
    <div id="right-panel">
      <p>Total Distance: <span id="total"></span></p>
    </div>
    
    <script>
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(initMap);
        } else { 
            alert("Geolocation is not supported by this browser.");
        }
        
        function initMap(position) {
        var currentLocation =  {lat: position.coords.latitude, lng: position.coords.longitude, label:'your location'} ;
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: {lat: {{ $resto->lat }}, lng: {{ $resto->lng }}} 
        });

        var directionsService = new google.maps.DirectionsService;
        var directionsRenderer = new google.maps.DirectionsRenderer({
          draggable: true,
          map: map,
          panel: document.getElementById('right-panel')
        });

        directionsRenderer.addListener('directions_changed', function() {
          computeTotalDistance(directionsRenderer.getDirections());
        });

        displayRoute(currentLocation, directionsService, directionsRenderer);
      }

      function displayRoute(origin, service, display) {
        service.route({
          origin: origin,
          destination:   {lat: {{ $resto->lat }}, lng: {{ $resto->lng }}, label: '{{ $resto->name }}'},
          travelMode: 'DRIVING',
          avoidTolls: true
        }, function(response, status) {
          if (status === 'OK') {
            display.setDirections(response);
          } else {
            alert('Could not display directions due to: ' + status);
          }
        });
      }

      function computeTotalDistance(result) {
        var total = 0;
        var myroute = result.routes[0];
        for (var i = 0; i < myroute.legs.length; i++) {
          total += myroute.legs[i].distance.value;
        }
        total = total / 1000;
        document.getElementById('total').innerHTML = total + ' km';
      }
    </script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlfh4WuZJz51yTzzIiopDiWIA1CmntLC0&callback=initMap" sync defer></script>
    </script>
    </div>
@endsection